### ISSUE TITLE
MiniMagick Support?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [topfunky/gruff#145]
I hear that RMagick is a memory hog, and MiniMagick would work better in the long run. When will you add support for it?

**Comment by donv** [comment]
Feel free to send us a pull request, and we will merge it and make a release.

**Comment by donv** [comment]
Hi @RailsCod3rFuture !

What does MiniMagick support mean?  What would have to be done?

**Comment by SamSaffron** [comment]
+1 on this these day rmagick does not even support the default stable version of image magick (7.0) 

Will investigate how complex a change like this is ...

**Comment by topfunky** [comment]
I did some research and realized that I had done the same research a long time ago.

Minimagick only does image resizing, not drawing. Gruff needs to draw lines, shapes, text, etc.

I'm exploring another option of rewriting a charting library in Go which has some more drawing capabilities (with others on the way in the new 2D libraries that are being developed). 

I could write that in a way that would shell out from Ruby in order to solve the memory problem.

**Comment by SamSaffron** [comment]
Interesting, a Go library absolutely helps, but I was wondering if this can be done more directly using the tooling image magick ships? 

Perhaps we could generate a conjure script, https://www.imagemagick.org/script/conjure.php and have it make the image?

**Comment by donv** [comment]
Does Minimagick still not offer drawing?  I see references to a #draw method, but I cannot find documentation or good examples.

**Comment by Watson1978** [comment]
I don't have a plan to support minimagick because RMagick already support ImageMagick 6 and ImageMagick 7 both.
